[package]
name = "ethers-structopt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.22"
ethers = "0.4.0"
color-eyre = "0.5.11"
